name: loops-qc
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - bedtools
  - meme
  - pandas>=1.3.0
  - numpy>=1.21.0
  - matplotlib>=3.4.0
  - pyyaml>=5.4.0
  - cooler>=0.9.0
  - cooltools>=0.5.0
